W0628 06:10:33.216000 2669666 site-packages/torch/distributed/run.py:766] 
W0628 06:10:33.216000 2669666 site-packages/torch/distributed/run.py:766] *****************************************
W0628 06:10:33.216000 2669666 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0628 06:10:33.216000 2669666 site-packages/torch/distributed/run.py:766] *****************************************
**********Test Starting************
Traceback (most recent call last):
  File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 193, in <module>
**********Test Starting************
Traceback (most recent call last):
  File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 193, in <module>
**********Test Starting************
Traceback (most recent call last):
  File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 193, in <module>
**********Test Starting************
Traceback (most recent call last):
  File "/scratch/mt/new-structure/experiments/msaeed/masters/SCA/MNIST/test-lca2.py", line 193, in <module>
    setup(rank, world_size)
          ^^^^
NameError: name 'rank' is not defined. Did you mean: 'range'?
    setup(rank, world_size)
          ^^^^
NameError: name 'rank' is not defined. Did you mean: 'range'?
    setup(rank, world_size)
          ^^^^
NameError: name 'rank' is not defined. Did you mean: 'range'?
    setup(rank, world_size)
          ^^^^
NameError: name 'rank' is not defined. Did you mean: 'range'?
W0628 06:11:02.694000 2669666 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669670 closing signal SIGTERM
W0628 06:11:02.704000 2669666 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669672 closing signal SIGTERM
W0628 06:11:02.705000 2669666 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 2669673 closing signal SIGTERM
E0628 06:11:02.840000 2669666 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 2669671) of binary: /home/m.saeed/miniconda3/envs/sca/bin/python3.12
Traceback (most recent call last):
  File "/home/m.saeed/miniconda3/envs/sca/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m.saeed/miniconda3/envs/sca/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
MNIST/test-lca2.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-28_06:11:02
  host      : gpunode01.imhotep.aic.gov.eg
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2669671)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
